language: python
python:
  - 2.7
  - 3.6

install:
  - python setup.py install
  - pip install cairosvg
  - wget -q -P /tmp https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/gh-pr-comment.sh
  - source /tmp/gh-pr-comment.sh

script:
  - eagle2svg ./tests/data/test.sch > test.sch.svg || (gh-pr-comment FAILED '`eagle2svg ./tests/data/test.sch` failed'; false)
  - eagle2svg ./tests/data/test.brd 0 1 20 17 18 21 25 19 > test-top.brd.svg || (gh-pr-comment FAILED '`eagle2svg ./tests/data/test.brd 0 1 20 17 18 21 25 19` failed'; false)
  - eagle2svg ./tests/data/test.brd 0 16 20 17 18 22 26 19 > test-bottom.brd.svg || (gh-pr-comment FAILED '`eagle2svg ./tests/data/test.brd 0 16 20 17 18 22 26 19` failed'; false)
  - cairosvg -f png -d 300 -o test.sch.png test.sch.svg
  - cairosvg -f png -d 450 -o test-top.brd.png test-top.brd.svg
  - cairosvg -f png -d 450 -o test-bottom.brd.png test-bottom.brd.svg
  - gh-pr-comment PASSED 'all tests passed'
