language: python
python:
  - 2.7
  - 3.6

install:
  - python setup.py install
  - pip install cairosvg==1.0.22 pycodestyle pyflakes
  - wget -q https://raw.githubusercontent.com/at-wat/gh-pr-comment/master/gh-pr-comment.sh

script:
  - ./tests/coding-style.sh
  - ./tests/exec-test.sh
