#!/usr/bin/env python

import sys

try:
    import eagle2svg.render
except ImportError:
    sys.exit('ERROR: Can\'t find required scripts.')

if __name__ == '__main__':
    eagle2svg.render.render_main(sys.argv)
