name: hide-old-bot-comments
on: pull_request

permissions:
  pull-requests: write

jobs:
  hide-old-bot-comments:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v6
      - name: Hide old bot comments
        uses: kamatama41/hide-pr-comments-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message_regex: "(Passed|Failed) on"
