name: release
on:
  push:
    tags:
        - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
      - name: Install build
        run: python -m pip install build
      - name: Lint
        run: python -m build
      - name: Deploy
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
