name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: at-wat/setup-gh-pr-comment@v0
      - name: Lint
        run: |
          python -m pip install cairosvg==1.0.22 pycodestyle pyflakes
          ./tests/coding-style.sh
      - name: Test
        run: |
          python -m pip install .
          ./tests/exec-test.sh
          sleep 5
        env:
          ALLOW_PUBLIC_UPLOADER: 1
          GITHUB_API_URL_BASE: https://ghbot-api.at-wat.tokyo
          GITHUB_TOKEN: bfac2435-4211-42ee-a1d6-0dfaf6b3b73d
