name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: |
          python -m pip install cairosvg==1.0.22 pycodestyle pyflakes gh-pr-comment
          ./tests/coding-style.sh
          python setup.py install
      - name: Test
        run: ./tests/exec-test.sh
